FROM ubuntu:jammy

ENV CC /usr/bin/clang
ENV CXX /usr/bin/clang++
ENV USER root

COPY etc/scripts/docker_packages.sh /setup/docker_packages.sh
RUN /setup/docker_packages.sh code_clean

COPY etc/scripts/docker_dependencies.pl /setup/docker_dependencies.pl
RUN /setup/docker_dependencies.pl code_clean

COPY ./ /src/cszb-scoreboard

RUN mkdir -p /src/cszb-scoreboard/out
WORKDIR /src/cszb-scoreboard/out

CMD echo "Please run etc/scripts/clean_code.pl"

